<a href="https://colab.research.google.com/github/mayurmahajan111/50projects50days/blob/master/dlassignment1_mayur(Linear_Regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install scikit-learn==1.1.0

#pip install tensorflow==2.11.1
#pip install numpy==1.22.4
#pip install pandas==1.4.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn==1.1.0 in /usr/local/lib/python3.10/dist-packages (1.1.0)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.1.0) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.1.0) (1.10.1)
Requirement already satisfied: joblib>=1.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.1.0) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn==1.1.0) (3.1.0)

In [3]:
# Importing the pandas for data processing and numpy for numerical computing
import numpy as np
import pandas as pd

In [4]:
# Importing the Boston Housing dataset from the sklearn
from sklearn.datasets import load_boston
boston = load_boston()

/usr/local/lib/python3.10/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
    :func:`~sklearn.datasets.fetch_california_housing`) and the Ames housing
    dataset. You can load the datasets as follows::

        from sklearn.datasets import fetch_california_housing
        housing = fetch_california_housing()

    for the California housing dataset and::

        from sklearn.datasets import fetch_openml
        housing = fetch_openml(name="house_prices", as_frame=True)

    for the Ames housing dataset.
  warnings.warn(msg, category=FutureWarning)

In [5]:
# Converting the data into pandas dataframe
data = pd.DataFrame(boston.data)

In [6]:
data.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33

In [7]:
# Adding the feature names to the dataframe
data.columns = boston.feature_names

In [8]:
# Adding the target variable to the dataset
data['PRICE'] = boston.target

In [9]:
# Looking at the data with names and target variable
data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2

In [10]:
# Checking the null values in the dataset
data.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
PRICE      0
dtype: int64

In [11]:
# Checking the statistics of the data
data.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,PRICE
count,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000,506.000000
mean,3.613524,11.363636,11.136779,0.069170,0.554695,6.284634,68.574901,3.795043,9.549407,408.237154,18.455534,356.674032,12.653063,22.532806
std,8.601545,23.322453,6.860353,0.253994,0.115878,0.702617,28.148861,2.105710,8.707259,168.537116,2.164946,91.294864,7.141062,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.082045,0.000000,5.190000,0.000000,0.449000,5.885500,45.025000,2.100175,4.000000,279.000000,17.400000,375.377500,6.950000,17.025000
50%,0.256510,0.000000,9.690000,0.000000,0.538000,6.208500,77.500000,3.207450,5.000000,330.000000,19.050000,391.440000,11.360000,21.200000
75%,3.677083,12.500000,18.100000,0.000000,0.624000,6.623500,94.075000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [12]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  PRICE    506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB

In [13]:
# X = data[['LSTAT','RM','PTRATIO']]
X = data.iloc[:,:-1]
y= data.PRICE

In [14]:
# Splitting the data into train and test for building the model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 4)

In [15]:
# Linear Regression
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()

In [16]:
# Fitting the model
regressor.fit(X_train,y_train)

LinearRegression()

In [17]:
# Prediction on the test dataset
y_pred = regressor.predict(X_test)

In [18]:
# Predicting RMSE the Test set results
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_pred)))
print(rmse)

5.041784121402048

In [19]:
# Scaling the dataset
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
# Creating the neural network model
import keras
from keras.layers import Dense, Activation,Dropout
from keras.models import Sequential
model = Sequential()
model.add(Dense(128,activation = 'relu',input_dim =13))
model.add(Dense(64,activation = 'relu'))
model.add(Dense(32,activation = 'relu'))
model.add(Dense(16,activation = 'relu'))
model.add(Dense(1))
model.compile(optimizer = 'adam',loss = 'mean_squared_error')

In [21]:
model.fit(X_train, y_train, epochs = 100)

Epoch 1/100
13/13 [==============================] - 2s 3ms/step - loss: 545.3366
Epoch 2/100
13/13 [==============================] - 0s 3ms/step - loss: 444.5740
Epoch 3/100
13/13 [==============================] - 0s 3ms/step - loss: 240.5450
Epoch 4/100
13/13 [==============================] - 0s 6ms/step - loss: 74.2750
Epoch 5/100
13/13 [==============================] - 0s 4ms/step - loss: 48.5086
Epoch 6/100
13/13 [==============================] - 0s 4ms/step - loss: 31.8063
Epoch 7/100
13/13 [==============================] - 0s 3ms/step - loss: 25.0283
Epoch 8/100
13/13 [==============================] - 0s 4ms/step - loss: 22.1599
Epoch 9/100
13/13 [==============================] - 0s 4ms/step - loss: 20.1608
Epoch 10/100
13/13 [==============================] - 0s 3ms/step - loss: 18.4162
Epoch 11/100
13/13 [==============================] - 0s 5ms/step - loss: 17.1838
Epoch 12/100
13/13 [==============================] - 0s 3ms/step - loss: 16.2771
Epoch 13/100
13/13 [==============================] - 0s 2ms/step - loss: 15.4131
Epoch 14/100
13/13 [==============================] - 0s 3ms/step - loss: 15.0127
Epoch 15/100
13/13 [==============================] - 0s 2ms/step - loss: 14.5830
Epoch 16/100
13/13 [==============================] - 0s 2ms/step - loss: 13.6182
Epoch 17/100
13/13 [==============================] - 0s 2ms/step - loss: 13.2559
Epoch 18/100
13/13 [==============================] - 0s 3ms/step - loss: 12.9863
Epoch 19/100
13/13 [==============================] - 0s 2ms/step - loss: 12.5359
Epoch 20/100
13/13 [==============================] - 0s 3ms/step - loss: 12.3704
Epoch 21/100
13/13 [==============================] - 0s 3ms/step - loss: 11.8302
Epoch 22/100
13/13 [==============================] - 0s 2ms/step - loss: 11.7071
Epoch 23/100
13/13 [==============================] - 0s 2ms/step - loss: 11.4231
Epoch 24/100
13/13 [==============================] - 0s 3ms/step - loss: 11.1020
Epoch 25/100
13/13 [==============================] - 0s 3ms/step - loss: 11.0398
Epoch 26/100
13/13 [==============================] - 0s 3ms/step - loss: 10.9159
Epoch 27/100
13/13 [==============================] - 0s 2ms/step - loss: 10.4998
Epoch 28/100
13/13 [==============================] - 0s 2ms/step - loss: 10.3490
Epoch 29/100
13/13 [==============================] - 0s 2ms/step - loss: 10.5164
Epoch 30/100
13/13 [==============================] - 0s 2ms/step - loss: 10.4552
Epoch 31/100
13/13 [==============================] - 0s 2ms/step - loss: 9.9534
Epoch 32/100
13/13 [==============================] - 0s 2ms/step - loss: 9.5887
Epoch 33/100
13/13 [==============================] - 0s 2ms/step - loss: 9.4430
Epoch 34/100
13/13 [==============================] - 0s 2ms/step - loss: 9.5294
Epoch 35/100
13/13 [==============================] - 0s 2ms/step - loss: 9.5139
Epoch 36/100
13/13 [==============================] - 0s 4ms/step - loss: 9.1129
Epoch 37/100
13/13 [==============================] - 0s 2ms/step - loss: 8.9036
Epoch 38/100
13/13 [==============================] - 0s 3ms/step - loss: 8.7647
Epoch 39/100
13/13 [==============================] - 0s 2ms/step - loss: 8.9320
Epoch 40/100
13/13 [==============================] - 0s 2ms/step - loss: 8.3480
Epoch 41/100
13/13 [==============================] - 0s 3ms/step - loss: 8.6718
Epoch 42/100
13/13 [==============================] - 0s 2ms/step - loss: 8.1685
Epoch 43/100
13/13 [==============================] - 0s 2ms/step - loss: 8.2619
Epoch 44/100
13/13 [==============================] - 0s 2ms/step - loss: 8.2249
Epoch 45/100
13/13 [==============================] - 0s 2ms/step - loss: 8.3790
Epoch 46/100
13/13 [==============================] - 0s 3ms/step - loss: 8.0321
Epoch 47/100
13/13 [==============================] - 0s 2ms/step - loss: 7.7825
Epoch 48/100
13/13 [==============================] - 0s 2ms/step - loss: 7.4624
Epoch 49/100
13/13 [==============================] - 0s 2ms/step - loss: 7.6565
Epoch 50/100
13/13 [==============================] - 0s 2ms/step - loss: 7.0895
Epoch 51/100
13/13 [==============================] - 0s 2ms/step - loss: 7.2860
Epoch 52/100
13/13 [==============================] - 0s 3ms/step - loss: 7.2524
Epoch 53/100
13/13 [==============================] - 0s 3ms/step - loss: 6.9373
Epoch 54/100
13/13 [==============================] - 0s 2ms/step - loss: 6.9512
Epoch 55/100
13/13 [==============================] - 0s 2ms/step - loss: 6.6888
Epoch 56/100
13/13 [==============================] - 0s 3ms/step - loss: 6.9351
Epoch 57/100
13/13 [==============================] - 0s 3ms/step - loss: 6.6279
Epoch 58/100
13/13 [==============================] - 0s 2ms/step - loss: 6.6357
Epoch 59/100
13/13 [==============================] - 0s 2ms/step - loss: 6.3667
Epoch 60/100
13/13 [==============================] - 0s 2ms/step - loss: 6.5102
Epoch 61/100
13/13 [==============================] - 0s 3ms/step - loss: 6.4568
Epoch 62/100
13/13 [==============================] - 0s 3ms/step - loss: 6.3885
Epoch 63/100
13/13 [==============================] - 0s 2ms/step - loss: 6.0699
Epoch 64/100
13/13 [==============================] - 0s 2ms/step - loss: 5.7812
Epoch 65/100
13/13 [==============================] - 0s 2ms/step - loss: 5.6084
Epoch 66/100
13/13 [==============================] - 0s 2ms/step - loss: 5.5618
Epoch 67/100
13/13 [==============================] - 0s 2ms/step - loss: 5.5207
Epoch 68/100
13/13 [==============================] - 0s 2ms/step - loss: 5.4494
Epoch 69/100
13/13 [==============================] - 0s 2ms/step - loss: 5.4311
Epoch 70/100
13/13 [==============================] - 0s 3ms/step - loss: 5.4229
Epoch 71/100
13/13 [==============================] - 0s 2ms/step - loss: 5.6762
Epoch 72/100
13/13 [==============================] - 0s 2ms/step - loss: 5.5260
Epoch 73/100
13/13 [==============================] - 0s 2ms/step - loss: 5.1455
Epoch 74/100
13/13 [==============================] - 0s 2ms/step - loss: 5.0514
Epoch 75/100
13/13 [==============================] - 0s 2ms/step - loss: 4.8314
Epoch 76/100
13/13 [==============================] - 0s 3ms/step - loss: 4.9647
Epoch 77/100
13/13 [==============================] - 0s 2ms/step - loss: 5.4084
Epoch 78/100
13/13 [==============================] - 0s 3ms/step - loss: 6.1020
Epoch 79/100
13/13 [==============================] - 0s 3ms/step - loss: 5.3767
Epoch 80/100
13/13 [==============================] - 0s 2ms/step - loss: 5.2017
Epoch 81/100
13/13 [==============================] - 0s 2ms/step - loss: 5.0811
Epoch 82/100
13/13 [==============================] - 0s 2ms/step - loss: 4.6351
Epoch 83/100
13/13 [==============================] - 0s 2ms/step - loss: 4.6838
Epoch 84/100
13/13 [==============================] - 0s 2ms/step - loss: 4.4772
Epoch 85/100
13/13 [==============================] - 0s 2ms/step - loss: 4.8490
Epoch 86/100
13/13 [==============================] - 0s 2ms/step - loss: 4.7339
Epoch 87/100
13/13 [==============================] - 0s 3ms/step - loss: 4.3848
Epoch 88/100
13/13 [==============================] - 0s 3ms/step - loss: 4.3554
Epoch 89/100
13/13 [==============================] - 0s 3ms/step - loss: 4.3790
Epoch 90/100
13/13 [==============================] - 0s 2ms/step - loss: 4.2476
Epoch 91/100
13/13 [==============================] - 0s 2ms/step - loss: 4.2646
Epoch 92/100
13/13 [==============================] - 0s 2ms/step - loss: 4.0362
Epoch 93/100
13/13 [==============================] - 0s 2ms/step - loss: 4.1922
Epoch 94/100
13/13 [==============================] - 0s 2ms/step - loss: 3.9561
Epoch 95/100
13/13 [==============================] - 0s 3ms/step - loss: 3.8806
Epoch 96/100
13/13 [==============================] - 0s 3ms/step - loss: 4.2290
Epoch 97/100
13/13 [==============================] - 0s 3ms/step - loss: 4.0614
Epoch 98/100
13/13 [==============================] - 0s 3ms/step - loss: 3.8728
Epoch 99/100
13/13 [==============================] - 0s 2ms/step - loss: 3.7227
Epoch 100/100
13/13 [==============================] - 0s 3ms/step - loss: 3.6390

In [22]:
y_pred = model.predict(X_test)

4/4 [==============================] - 0s 3ms/step

In [23]:
# Predicting RMSE the Test set results
from sklearn.metrics import mean_squared_error
rmse = (np.sqrt(mean_squared_error(y_test, y_pred)))
print(rmse)

3.208494731588567

In [24]:
# Making Predictions for testing data
np.set_printoptions(suppress=True)
result = model.predict(X_test)

4/4 [==============================] - 0s 3ms/step

In [25]:
df=pd.DataFrame(result, columns=['output'])
print(df)

        output
0    16.261393
1    23.699186
2    18.171644
3    19.159555
4    43.167614
..         ...
97   43.831978
98   16.044199
99   20.727367
100   8.431931
101  25.633383

[102 rows x 1 columns]